### ISSUE TITLE
[Android Bootcamp] Project 5: Twitter Client 2.0 - Ready for Review

### ISSUE THREAD

**Issue by ginacyliu** [ginacyliu/AndroidBootcamp#6]
My App is complete, please review. @nidhi1608, @codepathreview and @thecodepath

Time spent: 12 hours spent in coding

User Stories:
- [x] Includes all required user stories from Week 3 Twitter Client
- [x] User can switch between Timeline and Mention views using tabs.
  - [x] User can view their home timeline tweets.
  - [x] User can view the recent mentions of their username.
  - [x] User can scroll to bottom of either of these lists and new tweets will load ("infinite scroll")
  - [x] Optional: Implement this in a gingerbread-compatible approach
- [x] User can navigate to view their own profile
  - [x] User can see picture, tagline, # of followers, # of following, and tweets on their profile.
- [x] User can click on the profile image in any tweet to see another user's profile.
  - [x] User can see picture, tagline, # of followers, # of following, and tweets of clicked user.
  - [x] Profile view should include that user's timeline
  - [ ] Optional: User can view following / followers list through the profile
- [ ] Optional: When a network request goes out, user sees an indeterminate progress indicator
- [ ] Optional: User can "reply" to any tweet on their home timeline
  - [ ] The user that wrote the original tweet is automatically "@" replied in compose
- [ ] Optional: User can click on a tweet to be taken to a "detail view" of that tweet
  - [ ] Optional: User can take favorite (and unfavorite) or reweet actions on a tweet
- [ ] Optional: Improve the user interface and theme the app to feel twitter branded
- [ ] Optional: User can search for tweets matching a particular query and see results
- [ ] Stretch: User can view their direct messages (or send new ones)

Reference:
- Video1: https://player.vimeo.com/video/70911520
- Video2: http://yahoosales.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5af8c274-f2c8-4db1-8bca-ab917f545a90
- https://yahoo.jiveon.com/docs/DOC-3187
- https://yahoo.jiveon.com/docs/DOC-3188
- http://guides.codepath.com/android/Creating-and-Using-Fragments
- http://guides.codepath.com/android/ActionBar-Tabs-with-Fragments

**Comment by nidhi1608** [comment]
:+1: Project looks great. I have provided a detailed [Feedback Guide here](https://gist.github.com/nesquena/d88cf3606a308359323f) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you might be able to improve your submission.

Let us know if you have any other thoughts or questions about this assignment. Hopefully you can see this coming together as a "fully fledged" twitter client with some more work and polish. This app contains all of the components now (fragments, models, networking, client, tab navigation, image loading, et al) of 90% of dynamic data-driven API client. Obviously there are lots of details and patterns to learn, but by this point you have been introduced to all the major frameworks and concepts. Hopefully you would feel fairly confident getting started making Android apps for pinterest, yardsale or flickr using the same patterns.
